### PR TITLE
pull request

### PR DESCRIPTION
**Pull request by markmeulemans**
hi!!!

### CODE REVIEW

**Comment by LisaFC** [comment]
Hello! You're trying to commit changes to the docsy-example site repo rather than your own repo, just so you know.... It's a lovely website but it can't live in our repo :)

Maybe take another look at our Getting Started docs to make sure you have everything set up properly, and let me know if you have any problems: https://www.docsy.dev/docs/getting-started/

**Comment by LisaFC** [comment]
You're still trying to commit to our repo so none of these changes can be merged.....

**Comment by LisaFC** [comment]
You are *still* trying to commit to our project repo, not yours!

Please change the `origin` for your copy to your own project repo:
https://www.docsy.dev/docs/getting-started/#using-the-command-line

**Comment by LisaFC** [comment]
Hi folks, can you please switch the repo you're pushing to, this is not the right one!

**Comment by emckean** [comment]
Closing this PR

**Pull request closed without merging**
