### PR TITLE
Upgrade Docsy to v0.10.0-33-gfe0d785, add rtlcss pkg

### PR DESCRIPTION
**Pull request by chalin**
- Contributes to #295
- **Preview**: https://deploy-preview-322--goldydocs.netlify.app/fa/docs/

### Screenshot

Illustrates that the top-nav and footer are better than ever, in particular that the following have been fixed:

- https://github.com/google/docsy/issues/2005
- https://github.com/google/docsy/issues/2011

> image

Contrast this with the previous iteration, via #305:

- https://deploy-preview-305--goldydocs.netlify.app/fa/docs/

### CODE REVIEW

**Comment by chalin** [comment]
@theletterf - can PTAL

**Comment by chalin** [comment]
Merging now. @theletterf - feedback is still welcome.

**Comment by theletterf** [comment]
FWIW it looks good to me!

Could the feedback feature get translated?

**Comment by chalin** [comment]
> FWIW it looks good to me!

Thank you!

> Could the feedback feature get translated?

Yes, I've been waiting for a kind soul to submit a PR for https://github.com/google/docsy/issues/2019 😄

**Pull request merged**
