### PR TITLE
update package.json and package-lock.json

### LINKED ISSUE #45: package.json references non-existent tech-doc-hugo project
This project's package.json file (and the main docsy userguide's source) seem to have been imported intact from `https://github.com/bep/tech-doc-hugo`.

I scratched my head a bit and decided that it probably didn't really matter because it's just being used as a mechanism to declare dev dependencies on postcss and autoprefixer, but wanted to confirm my understanding.

If I'm using this project as the basis for a new docs site, is there any point (or harm) in updating it?

### PR DESCRIPTION
**Pull request by hegemonic**
+ Update dev dependencies to latest versions. (I confirmed that running `hugo server` and viewing the site works as expected.)
+ Fix URLs in package file.

Fixes #45.

### CODE REVIEW

**Comment by hegemonic** [comment]
Based on the logs, I think the Netlify deploy is failing because it's using Node.js 8.17.0, which reached its end of life on 2019-12-31. As a result, many packages have dropped support for Node.js 8.x.

I suggest upgrading to Node.js 12.16.3, which is the Active Long-Term Stable (LTS) version. Alternatively, you could upgrade to Node.js 10.20.1, the Maintenance LTS version, which will be maintained through 2021-04-30.

The Node.js website has more [details about the LTS timeline](https://nodejs.org/en/about/releases/).

**Comment by LisaFC** [comment]
That's very odd, the Netlify preview deploy actually works fine (I just redeployed it to be sure) so I'm not sure where the errors are coming from. The build image used by default on Netlify uses Node 10. If you're happy this isn't going to cause any oddities to users deploying on Netlify I'm happy to merge.

**Comment by LisaFC** [comment]
I'm going to merge this and sure if it causes problems in the live site I can revert it..... *crosses fingers*

**Comment by LisaFC** [comment]
No deploy errors so I'm not sure what the initial problem was. Thanks for the fix!

**Pull request merged**
