### PR TITLE
Add Docker image to run docsy-example locally

### PR DESCRIPTION
**Pull request by geriom**
Docker image to run docsy-example locally without having to install all the dependencies.

### CODE REVIEW

**Comment by LisaFC** [comment]
BTW I manually reran the deploy preview and all checks passed so no need to worry about that previous failed check - as I said, I think it happened a few times when the Netlify servers couldn't get a response from Github in time.

**Comment by LisaFC** [comment]
Also this is great! Can you also add a PR to the docs in the main docsy repo - maybe to https://www.docsy.dev/docs/deployment/

**Comment by geriom** [comment]
Sorry for the delay, I submitted https://github.com/google/docsy/pull/387. I opted for a quickstart, instead of a section in deployment, to make it the entry point for new users. Hopefully this will get them up and running in just a few minutes.

**Comment by LisaFC** [comment]
Great, going to merge this now

**Pull request merged**
