### PR TITLE
Content: directory rename (avoid mixed case and spaces), and front matter cleanup

### PR DESCRIPTION
**Pull request by deining**
As already pointed out in an docsy [issue](https://github.com/google/docsy/issues/770#issue-1055298045), we should avoid mixed-case directory names and names containing spaces for content sections. The docsy example has such sections, too. This PR corrects this.

### CODE REVIEW

**Review by chalin — APPROVED** [review]
✨

**Comment by deining** [comment]
Glad to see this merged, but ...

It came to my mind that we still do have PR #241 which brings in the Chinese translation to the example site. In case we want to consider this PR, we should have brought this PR in prior to changing the folder names and file names ad done with this just merged PR. If we leave it as is, a lot of rework is required for the translation PR, I guess. WDYT?

**Comment by chalin** [comment]
The two PRs have mutually exclusive content so the order doesn't matter IMHO. Can I let you inform the PR author of the changes that will be required (which don't seem to be too extensive)? Then again, I'm not convinced that we want another example language. Let's discuss this further in:

- #251 

Maybe it's best just to let the author know that we're assessing the PR, but that if it's accepted it will need to conform to the new directory structure and names.

**Comment by deining** [comment]
> Maybe it's best just to let the author know that we're assessing the PR, but that if it's accepted it will need to conform to the new directory structure and names.

Agreed. Let's wait for the decision of PSC.

**Pull request merged**
