### PR TITLE
Dockerfile: use base image with extended version of Hugo

### PR DESCRIPTION
**Pull request by dseynaev**

### CODE REVIEW

**Comment by dseynaev** [comment]
@googlebot I signed it!

**Comment by LisaFC** [comment]
@geriom do you want to take a look at this?

**Comment by geriom** [comment]
I can't currently test this because of a breaking change in the example. As soon as that is resolved I'll look into this.

**Review by geriom — CHANGES_REQUESTED** [review]
Instead of `klakegg/hugo:0.81.0-ext-asciidoctor` use `hugo:ext-alpine`. This way we guarantee that we always use the latest version and don't have to update it after every hugo release.

**Review by geriom — APPROVED** [review]
Thank you!

**Pull request merged**
